---
- name: Instalar Postman
  hosts: localhost
  become: yes
  tasks:
    - name: Descargar Postman
      get_url:
        url: https://dl.pstmn.io/download/latest/linux64
        dest: /tmp/postman.tar.gz

    - name: Extraer Postman
      unarchive:
        src: /tmp/postman.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Crear enlace simbólico para Postman
      file:
        src: /opt/Postman/Postman
        dest: /usr/bin/postman
        state: link