---
- name: Install Conda
  hosts: all
  become: yes
  tasks:
    - name: Download Miniconda installer
      get_url:
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /tmp/Miniconda3-latest-Linux-x86_64.sh
        mode: '0755'

    - name: Run Miniconda installer
      command: bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda

    - name: Add Conda to the PATH
      lineinfile:
        path: /etc/profile.d/conda.sh
        line: 'export PATH="/opt/miniconda/bin:$PATH"'
        create: yes

    - name: Source the Conda profile script
      shell: source /etc/profile.d/conda.sh
      args:
        executable: /bin/bash